/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'Home',
    {
      type: 'category',
      label: 'iOS基础知识',
      items: [
        'iOSBase/TaggerPointer',
        {
          type: 'category',
          label: '02 | weak 底层实现原理',
          items: [
            'iOSBase/weak/weak底层实现原理一',
            'iOSBase/weak/weak底层实现原理二：objc-weak函数列表全解析',
            'iOSBase/weak/weak底层实现原理三：weak_entry_t',
            'iOSBase/weak/weak底层实现原理四：weak变量从初始化到被置为nil都经历了什么',
            'iOSBase/weak/weak底层实现原理五：ARC和MRC下weak变量的访问过程',
            
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '计算机基础知识',
      items: [
        '计算机基础知识/位运算按位取反',
      ],
    },
    {
      type: 'category',
      label: '逆向与安全',
      items: [
        '逆向与安全/签名',
        '逆向与安全/注入闪退相关',
        {
          type: 'category',
          label: 'ARM 汇编基础',
          items: [
            '逆向与安全/ARM/ARM汇编总览',
            '逆向与安全/ARM/寄存器',
            '逆向与安全/ARM/指令集',
            '逆向与安全/ARM/栈及传参规则',
            '逆向与安全/ARM/具体指令使用细节',
            '逆向与安全/ARM/if_switch_循环',
            
          ],
        },
        {
          type: 'category',
          label: 'Frida 使用',
          items: [
            '逆向与安全/Frida/在iOS上分析应用',
            '逆向与安全/Frida/Hook大法，拦截器的使用',
            '逆向与安全/Frida/如何拦截sub_xxxx这种函数',
            '逆向与安全/Frida/API查找器和拦截器的组合使用',
            '逆向与安全/Frida/远程过程调用RPC的使用方法',
            '逆向与安全/Frida/非越狱环境下使用Frida',
            '逆向与安全/Frida/总结',
            
          ],
        },
      ],
    },
  ],
};
