/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'Home',
    {
      type: 'category',
      label: 'iOS',
      items: [
        {
          type: 'category',
          label: '源码分析',
          items: [
            'iOS/源码分析/TaggerPointer',
            {
              type: 'category',
              label: '02 | weak 底层实现原理',
              items: [
                'iOS/源码分析/weak/weak底层实现原理一',
                'iOS/源码分析/weak/weak底层实现原理二：objc-weak函数列表全解析',
                'iOS/源码分析/weak/weak底层实现原理三：weak_entry_t',
                'iOS/源码分析/weak/weak底层实现原理四：weak变量从初始化到被置为nil都经历了什么',
                'iOS/源码分析/weak/weak底层实现原理五：ARC和MRC下weak变量的访问过程',
              ],
            },
            'iOS/源码分析/associatedObject',
          ],
        },
        {
          type: 'category',
          label: '碎片知识整理',
          items: [
            'iOS/碎片知识整理/AVPlayer截取视频流的当前帧',
          ],
        },
        {
          type: 'category',
          label: '文章收录',
          items: [
            'iOS/文章收录/基础知识整理',
            'iOS/文章收录/二进制重排',
            'iOS/文章收录/启动优化',
            'iOS/文章收录/组件化文章',
          ],
        },
        {
          type: 'category',
          label: '工具',
          items: [
            'iOS/工具/fastlane',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '计算机基础知识',
      items: [
        '计算机基础知识/位运算按位取反',
      ],
    },
    {
      type: 'category',
      label: '逆向与安全',
      items: [
        '逆向与安全/签名',
        '逆向与安全/注入闪退相关',
        {
          type: 'category',
          label: 'ARM 汇编基础',
          items: [
            '逆向与安全/ARM/ARM汇编总览',
            '逆向与安全/ARM/寄存器',
            '逆向与安全/ARM/指令集',
            '逆向与安全/ARM/栈及传参规则',
            '逆向与安全/ARM/具体指令使用细节',
            '逆向与安全/ARM/if_switch_循环',
            
          ],
        },
        {
          type: 'category',
          label: 'Frida 使用',
          items: [
            '逆向与安全/Frida/在iOS上分析应用',
            '逆向与安全/Frida/Hook大法，拦截器的使用',
            '逆向与安全/Frida/如何拦截sub_xxxx这种函数',
            '逆向与安全/Frida/API查找器和拦截器的组合使用',
            '逆向与安全/Frida/远程过程调用RPC的使用方法',
            '逆向与安全/Frida/非越狱环境下使用Frida',
            '逆向与安全/Frida/总结',
            
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '招聘一个靠谱的iOS',
      items: [
        '招聘一个靠谱的iOS/面试题一：属性关键字',
        '招聘一个靠谱的iOS/面试题二',
        '招聘一个靠谱的iOS/reverse-interview',
      ],
    },
  ],
};
